name: Daniel Durrant
favicon: null
layout_spectrum: 1
typography_spectrum: 0.27602
title: facets of experimentation
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#8f8f8f'
    - '#474747'
    - '#4efc96'
  brandStrength: 1
  lightness: 0.375
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
