name: Daniel Durrant
favicon: null
layout_spectrum: 0.17599
typography_spectrum: 0.09705
title: facets of an experiment
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#8f8f8f'
    - '#474747'
    - '#4efc96'
  brandStrength: 0.8284075616393238
  lightness: 0.39896604930981994
  saturation: 0.3594324183650315
  rhythmicContrast: 0.8070922440383583
purpose: []
